return {
    "NvChad/nvim-colorizer.lua",
    event = { "BufReadPost", "BufNewFile" },
    opts = {
        filetypes = {
            "*",
            "!lazy",
            "!mason",
            "!copilot-chat",
            "!copilot-input",
            "!snacks_picker_input",
            "!snacks_explorer",
            "!noice",
            "!prompt",
            "!notify",
            "!toggleterm",
            "!Trouble",
        },
        buftypes = {
            "*",
            "!nofile",
            "!prompt",
            "!terminal",
            "!quickfix",
        },
        user_default_options = {
            RGB = true,
            RRGGBB = true,
            names = true,
            RRGGBBAA = true,
            AARRGGBB = true,
            rgb_fn = true,
            hsl_fn = true,
            css = true,
            css_fn = true,
            mode = "virtualtext",
            tailwind = true,
            sass = { enable = true, parsers = { css = true } },
            virtualtext = "󰝤 ",
            always_update = true,
        },
    },
}
