return {
    "nvim-tree/nvim-web-devicons",
    event = "VeryLazy",
    config = function()
        local devicons = require("nvim-web-devicons")

        devicons.setup({
            default = true,
            color_icons = true,
            strict = true,
            override = {
                default_icon = {
                    icon = "󰈔",
                    color = "#cdd6f4",
                    name = "Default",
                },
            },
            override_by_filename = {
                [".gitignore"] = { icon = "", color = "#f34f29", name = "GitIgnore" },
                [".gitattributes"] = { icon = "", color = "#f34f29", name = "GitAttributes" },
                [".zshrc"] = { icon = "", color = "#89dceb", name = "Zshrc" },
                [".bashrc"] = { icon = "", color = "#89dceb", name = "Bashrc" },
                ["README.md"] = { icon = "󰍔", color = "#fab387", name = "Readme" },
                ["LICENSE"] = { icon = "󰿃", color = "#f9e2af", name = "License" },
                ["init.lua"] = { icon = "", color = "#51a0cf", name = "InitLua" },
                ["lazy-lock.json"] = { icon = "󰒲", color = "#cba6f7", name = "LazyLock" },
                ["package.json"] = { icon = "󰎙", color = "#cb3837", name = "PackageJson" },
                ["tsconfig.json"] = { icon = "", color = "#3178c6", name = "TsConfig" },
                ["tailwind.config.js"] = { icon = "󱏿", color = "#06b6d4", name = "TailwindConfigJs" },
                ["tailwind.config.ts"] = { icon = "󱏿", color = "#06b6d4", name = "TailwindConfigTs" },
                ["Dockerfile"] = { icon = "󰡨", color = "#2496ed", name = "Dockerfile" },
                ["docker-compose.yml"] = { icon = "󰡨", color = "#2496ed", name = "DockerCompose" },
                ["Makefile"] = { icon = "", color = "#6d8086", name = "Makefile" },
                ["CMakeLists.txt"] = { icon = "", color = "#064f8c", name = "CMakeLists" },
            },
            override_by_extension = {
                lua = { icon = "", color = "#51a0cf", name = "Lua" },
                md = { icon = "󰍔", color = "#fab387", name = "Markdown" },
                txt = { icon = "󰈙", color = "#cdd6f4", name = "Text" },
                json = { icon = "󰘦", color = "#f9e2af", name = "Json" },
                toml = { icon = "󰰤", color = "#a6e3a1", name = "Toml" },
                yaml = { icon = "󰈙", color = "#f5c2e7", name = "Yaml" },
                yml = { icon = "󰈙", color = "#f5c2e7", name = "Yml" },
                sh = { icon = "", color = "#4eb899", name = "Sh" },
                zsh = { icon = "", color = "#4eb899", name = "Zsh" },
                bash = { icon = "", color = "#4eb899", name = "Bash" },
                js = { icon = "", color = "#f7df1e", name = "Js" },
                jsx = { icon = "", color = "#61dafb", name = "Jsx" },
                ts = { icon = "", color = "#3178c6", name = "Ts" },
                tsx = { icon = "", color = "#61dafb", name = "Tsx" },
                html = { icon = "", color = "#e44d26", name = "Html" },
                css = { icon = "", color = "#42a5f5", name = "Css" },
                scss = { icon = "", color = "#c6538c", name = "Scss" },
                py = { icon = "", color = "#ffbc03", name = "Python" },
                rs = { icon = "", color = "#dea584", name = "Rust" },
                go = { icon = "", color = "#00add8", name = "Go" },
                c = { icon = "", color = "#599eff", name = "C" },
                cpp = { icon = "", color = "#519aba", name = "Cpp" },
                h = { icon = "", color = "#a074c4", name = "H" },
                hpp = { icon = "", color = "#a074c4", name = "Hpp" },
                sql = { icon = "󰆼", color = "#dad8d8", name = "Sql" },
            },
        })
    end,
}
